### PR TITLE
PR continued from the previous one

### PR DESCRIPTION
**Pull request by TheNova22**
Hey @scitbiz,
Made squash in the recent commits and made several of these commits into just 2 commits, the previous commits as they are outdated, i am facing an issue in squashing them up. But the recent commits made after the changes were requested in the previous PR has been squashed. Over all, this PR is ready to be merged.
Sorry about the inconvenience caused by my constant notifications.

### CODE REVIEW

**Comment by scitbiz** [comment]
Hi @TheNova22, 
I still see some duplicated commit and some unnecessary commits. Can you squash them to only 3-4 commits?

**Comment by TheNova22** [comment]
Hey @scitbiz,
Could you check if this is alright to merge? As i encountered some conflicts when squashing, so had to resolve them. These i avoided last time as i wasn’t yet sure because the merge of your rebase and master happened and i had to update my upstream, hence i might have faced some squash issues over there. Hope this is alright. Else do inform steps to be taken.
Thank you for having the patience even when i did the silly error of doing too many commits :)

**Comment by scitbiz** [comment]
@TheNova22 Thanks for taking the time to contribute to this project. Hope to see more commits like this from you!

**Comment by TheNova22** [comment]
Thanks for making the merge, will continue to contribute to this project :)

**Pull request merged**
