### PR TITLE
resolve #20

### LINKED ISSUE #20: Weird snapping back when scrolling up in main page
The app looks great! Minor criticism: on the main page, if you swipe up a very small distance and quickly, it snaps back down. This looks weird and unnecessary. Not sure whether it's intentional, but it looks like a bug.

I noticed it on Android and iOS devices, with https://github.com/scitbiz/flutter_pokedex/commit/1844ab23b427d56de63e6ce2b0c292aa57a5c3d3

### PR DESCRIPTION
**Pull request by shivanigupta19**
issue solved by shivani #20
Please close the issue.

### CODE REVIEW

**Comment by scitbiz** [comment]
@shivanigupta19 Hi, thanks for creating this pull request. 
Due to the lack of a message of @i-schuetz, I will consider it will fix this issue because it only has a small effect on the project.
Please rename your commit and pull title to something meaningful (like `resolve #20`). Also, remove all unnecessary changes and only focusing on the change which fixed the issue. 

Thanks again!

**Comment by shivanigupta19** [comment]
@scitbiz  sorry please clear your sentence again

**Comment by scitbiz** [comment]
@shivanigupta19, please also change your commit message to `resolve #20` and uncommit the `pubspec.lock` file. Thanks!

**Comment by scitbiz** [comment]
I'll close this issue here because there is no action coming up and the master branch has changed. If you still want to fix this issue, please open a new pull request based on the new `master` branch. Thank you!

**Pull request closed without merging**
