### PR TITLE
Update generations icons

### PR DESCRIPTION
**Pull request by jitinder**
Thought about adding some updates to the generations page - it only showed the first generation. Added images of all starters from all 8 generations

### CODE REVIEW

**Comment by scitbiz** [comment]
@jitinder please rebase your code

**Comment by jitinder** [comment]
Hi @scitbiz , I just rebased my code. Should I create a new PR? (sorry, its my first ever open-source contribution)

**Comment by scitbiz** [comment]
@jitinder After rebasing your code in the local, you can push to your fork repo with `git push <your-remote> <your-branch> -f`.

For example: `git push origin updates -f`

**Comment by jitinder** [comment]
@scitbiz Let me know if what i did is alright... thanks for your guidance :)

**Comment by scitbiz** [comment]
Hmm, it seems like something wrong with your repo.

Your `master` branch should be exactly like this repo. And you should not merge/pull the `master` branch to your `updates` branch, only rebase it.

And now to fix it, first you need to reset your master branch to match this repo:
https://stackoverflow.com/a/42332860/6659074

Next, create a new branch from the master branch:
`git checkout master`
`git checkout -b update-generation-icons`

Next, cherry-pick the commit you want (`Update generations icons`):
`git log` to get the commit hash of `Update generations icons`
`git cherry-pick <your-commit-hash>`

Now add, commit all changed files and push to create a new pull request

(Optional: You can remove the old branch, rename the new branch to the old names, and then force push so you don't need to create a new pull)

**Comment by jitinder** [comment]
Wow, I didn't even know half of these things... Thanks for your patience. I hope the latest update is done correcty.

**Comment by scitbiz** [comment]
@jitinder It looks great now. Thank you so much!

**Pull request merged**
