### PR TITLE
Fetching basic news.

### PR DESCRIPTION
**Pull request by meta-boy**
Fetching news from https://www.pokemon.com/us/pokemon-news/

Not sure if this was something you guys planned on writing as its nowhere mentioned in the [README.md](https://github.com/scitbiz/flutter_pokedex/blob/master/README.md). This is just a basic implementation as of now, let me know if this feature is appreciated then will work towards making a much cleaner and beautiful looking news module for this app.

### CODE REVIEW

**Comment by scitbiz** [comment]
Hi, @meta-boy 
Could you please using `dio` instead of `webview_flutter` or `http`. I'm currently refactoring the codebase and using `dio` in this project.
And replace the `Image.network` with `cached_network_image`, use its `placeholder` or `progressIndicatorBuilder` properties for better UX.

This is the one I'm planning to add, so if you can contribute it will be awesome. 
Thanks for your pull request!

**Comment by meta-boy** [comment]
> Hi, @meta-boy
> Could you please using `dio` instead of `webview_flutter` or `http`. I'm currently refactoring the codebase and using `dio` in this project.

Yeah, I can definitely do that, also I installed `webview_flutter` as to open news articles (as the API does not provide the body for the news) which I haven't implemented yet.

> And replace the `Image.network` with `cached_network_image`, use its `placeholder` or `progressIndicatorBuilder` properties for better UX.

Yes, ideally I would do this too but given that it wasn't already used, I didn't use it as well.

> This is the one I'm planning to add, so if you can contribute it will be awesome.

I'm sorry I didn't understand quite well... Have you already written code for the news part of the app?

> Thanks for your pull request!

You're welcome  ^^

**Comment by scitbiz** [comment]
> Yeah, I can definitely do that, also I installed `webview_flutter` as to open news articles (as the API does not provide the body for the news, I just might scrape it right off the webpage) which I haven't implemented yet.

Scraping might be risky because it depends on the web structure, which can be changed over time. So it's safer to open on device's browser if there is no API for this yet.

> Yes, ideally I would do this too but given that it wasn't already used, I didn't use it as well.

The `cached_network_image` pub is already in the project. You should better use it.

> I'm sorry I didn't understand quite well... Have you already written code for the news part of the app?

No, currently not.

**Comment by meta-boy** [comment]
> Scraping might be risky because it depends on the web structure, which can be changed over time. So it's safer to open on device's browser if there is no API for this yet.

Yeah true.

> The `cached_network_image` pub is already in the project. You should better use it.

Oh yes seems like I missed it ^^'

> No, currently not.

gotcha.

I'll close this PR and make another one pointing to the [refactor](https://github.com/scitbiz/flutter_pokedex/tree/refactor) branch.

**Comment by scitbiz** [comment]
Great, thanks!

**Pull request closed without merging**
