### PR TITLE
Added base stats and added all info in about page except location .Added items.json

### PR DESCRIPTION
**Pull request by balvinderz**
Added base stats and added all info in about page except location .Added items.json for future use.

### CODE REVIEW

**Comment by balvinderz** [comment]
can you merge this or is there any problem in the code ?

**Comment by scitbiz** [comment]
Sorry, I got busy these days. I will review and merge your pull request when I have free time

**Comment by balvinderz** [comment]
okay

**Comment by scitbiz** [comment]
Thank you!

**Pull request merged**
