### PR TITLE
Add data for Abilities till gen 7

### PR DESCRIPTION
**Pull request by jitinder**
Added a Model and Data for all abilities till gen 7 by parsing data from PokeAPI

### CODE REVIEW

**Comment by scitbiz** [comment]
1. Are you planning to apply this to the `Moves` tabs? 
2. I'm currently moving data to gist and fetch data from there. So if you can create a json version like the pokemons.json and items.json, it will be awesome

**Comment by jitinder** [comment]
I was planning to add this for the future, whenever we need to use abilities :P Will put it as a JSON instead and push

**Comment by jitinder** [comment]
@scitbiz Have a look at the JSON and host it as a gist as per your requirement. Its formatted using jsonformatter for your convenience...

**Comment by scitbiz** [comment]
@jitinder Awesome, thanks!

**Pull request merged**
