### PR TITLE
Made a few changes, additions and added comments in few files for better understanding

### PR DESCRIPTION
**Pull request by TheNova22**
First of all, i would like to tell that i loved the app and the idea behind it, as i too am a fellow pokemon fan.
So, the changes or additions made were:

- Added comments to a few files that might help future contributors understand what's happening quicker.

- Made a moves.json file and a class called Moves that can be used to display various moves to users.

- In order to avoid bottom overflow in few regions, altered the already written code a bit, for example : in the base stats region of pokedex, the user couldn't view all the effective types, hence made changes to that by making it similar to the info tab. Hence, now it works like a charm.

(All the following were tested in android devices and not iOS as it failed to run it)
These are the current changes/additions made by me and i will also further continue commiting to this repo. My next goal ahead will be to successfully implement the moves section by which, when a user clicks on Moves button from the category list in the home page, he/she will be redirected to a page which will then display all the moves present in our json file.

Hope you merge it :)

### CODE REVIEW

**Comment by scitbiz** [comment]
Hi @TheNova22,
First of all, I really appreciate your contribution. I'm working on refactoring the project at #13 and planning to merge it at the weekend. If you can update this pull request for the `refactor` branch, that would be great!

**Comment by TheNova22** [comment]
Changed the branch to the refactor branch. And hence there are some conflicts being formed. Hope you look into it when you get time.
Thanks and hoping to see it merged :)
Will continue checking out the refactor branch from now and making changes and commits over there.

**Comment by hungps-2150** [comment]
@TheNova22 Actually I cannot know which files you are changing so it would be great if you can apply all the changes to `refactor` branch because the commit is a little bit messy here.

Sorry for the inconvenience and hope you can understand. Can't wait to merge your pull request :D

**Comment by scitbiz** [comment]
@TheNova22 Actually I cannot know which files you are changing so it would be great if you can apply all the changes to refactor branch because the commit is a little bit messy here.

Sorry for the inconvenience and hope you can understand. Can't wait to merge your pull request :D

**Comment by TheNova22** [comment]
Sure! Will be happy to do so..Thanks for the quick reply :)

**Pull request closed without merging**
